### PR TITLE
Update CMake build/install instructions

### PR DESCRIPTION
**Pull request by herzenschein**
This PR updates the build instructions to:

* not use the old unnecessary mkdir build && cd build process
* not depend explicitly on make
* not show the build directory by default
* install in /usr instead of /usr/local by default (not all distros have /usr/local set IIRC)
* make it more obvious that the install prefix can be changed and how (handy if you want to install to ~/.local)

Unfortunately since the .in file's variable is processed at build time, I did not find a way to use --prefix instead of CMAKE_INSTALL_PREFIX, which would have made the instructions nicer.

### CODE REVIEW

**Comment by dangvd** [comment]
Thank you very much!

Would you mind updating the "make test" bit as well please? I know the
tests are failing atm due to recent changes but I'll update them soon.

**Comment by dangvd** [comment]
Never mind, I'll update the other bit.

**Comment by dangvd** [comment]
I've updated this page btw:
https://github.com/dangvd/crystal-dock/wiki/Author-&-Contributors

**Comment by herzenschein** [comment]
Aw, I was going to finish it this evening :P

The way to do it in a more practical way is by using `ctest --test-dir build/` (requires CMake 3.20), it doesn't matter whether you use make, ninja, gmake or whatever since it's managed by CMake. Naturally you can always `cd build && ctest` as well.

Using `cmake --build build/ --target test` is both longer and rather impractical since if you want to pass something like --output-on-failure you'd need something like `CTEST_OUTPUT_ON_FAILURE=ON cmake --build build --target test`.

**Comment by dangvd** [comment]
Thanks, I've updated the test instructions.

**Pull request merged**
