### PR TITLE
New feature (look great): Feature: Always On Top visibility option #33

### PR DESCRIPTION
**Pull request by factrc**

### CODE REVIEW

**Comment by dangvd** [comment]
Hi,

Thanks for your change but this doesn't really work. I did test an implementation like this and as I described in #33:

Quoting:

Specifically, on X11, the dock resizes to small size when minimized and resizes to big size when zoomed in. On Wayland, resizing would cause graphical glitch so now I have to keep the size big all the time and when minimized only make a small part of it visible. So if I enable Always On Top now, the dock will take too much space and get into your way -- for example, it will capture your mouse/keyboard input in the big area even though it's invisible in the outer part. I tried using widget masking to enable mouse/keyboard input only in the small area but it didn't work for some reason.

**Comment by factrc** [comment]
Hi,
I don't quite understand how the panel should look in this case, i haven't
used crystal-dock 1.0 on X11.
However, I wanted there to be an alternative, "by button", for those cases
who are satisfied with it.
It's still better than nothing.

Thanks a lot!


ср, 21 авг. 2024 г. в 17:54, Viet Dang ***@***.***>:

**Comment by dangvd** [comment]
Hi,

The look is good. The problem is the mouse/keyboard input capture in the bigger area around the dock.
So we need to find a way to mask the dock so that the mouse/keyboard input only gets sent to the dock if the input is in the visible area of the dock.

**Comment by dangvd** [comment]
Hi,

I've found a way to fix the mouse input issue: https://github.com/dangvd/crystal-dock/commit/a3093271582c5a0a6060c87007989435a40cc6c8

so I've added the Always On Top visibility option in: https://github.com/dangvd/crystal-dock/commit/60a9ae918a976b76e43f50599bf57019ecee0064
(similar to your PR)

So I will close this PR then.
Thank you!

**Pull request closed without merging**
